/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:a770773f-e460-442b-9204-fcf7ca8e5d4c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_xa0Ka9jOk",
    "aws_user_pools_web_client_id": "5mrgqolao55smkuur6t4im6anf",
    "oauth": {}
};


export default awsmobile;
