# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master and dev branch
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 1: setup node
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.11.0
          
      # 2: Checkout repository in the CWD
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Run a script
        run: |
          ls
          touch .env
          echo REACT_APP_AWS_ACCESS_KEY_ID=${{secrets.REACT_APP_AWS_ACCESS_KEY_ID}} >> .env
          echo REACT_APP_AWS_SECRET_ACCESS_KEY=${{secrets.REACT_APP_AWS_SECRET_ACCESS_KEY}} >> .env
          echo REACT_APP_AWS_TEMPLATE_API_KEY=${{secrets.REACT_APP_AWS_TEMPLATE_API_KEY}} >> .env
          echo REACT_APP_AWS_TEMPLATE_LOG_API_KEY=${{secrets.REACT_APP_AWS_TEMPLATE_LOG_API_KEY}} >> .env
          echo REACT_APP_AWS_SINGLE_EMAIL_API_KEY=${{secrets.REACT_APP_AWS_SINGLE_EMAIL_API_KEY}} >> .env
          cat .env

      # 3: install NPM dependencies
      - name: Install dependencies
        run: npm install
      
      # 4: run test command
      - name: Run unit test command
        run: npm run test:unit
      
      # 5: run integration tests command
      - name: Run integration test command
        run: npm run test:integration
